Repository gravityflow/gravityflow, pull requests merged in 2019-02, with the labels that each got.

#199 Add back link to shortcode
  change_log.txt
  class-gravity-flow.php
  includes/class-gravityview-detail-link.php
  includes/pages/class-entry-detail.php
Labels: enhancement

#200 Search criteria
  change_log.txt
  includes/pages/class-status.php
Labels: enhancement

#211 Fix spikes in licensing requests
  class-gravity-flow.php
  includes/class-extension.php
  includes/class-feed-extension.php
Labels: enhancement

#207 Fix issue with GFlow API get_timeline
  change_log.txt
  includes/class-api.php
  includes/class-common.php
  includes/merge-tags/class-merge-tag-workflow-note.php
  includes/merge-tags/class-merge-tag-workflow-timeline.php
  includes/merge-tags/class-merge-tags.php
Labels: bug

#205 Allow wp e-signature redirect if processed before confirmation displayed
  includes/steps/class-step-feed-wp-e-signature.php
Labels: enhancement

#213 Add license check throttling
  class-gravity-flow.php
  includes/class-extension.php
  includes/class-feed-extension.php
Labels: enhancement

#206 Add shortcode security settings
  class-gravity-flow.php
  includes/pages/class-entry-detail.php
Labels: bug, enhancement

#218 Add extension license key constant
  class-gravity-flow.php
  includes/class-extension.php
  includes/class-feed-extension.php
  includes/wizard/steps/class-iw-step-license-key.php
Labels: enhancement

#222 Fix OAuth1.0a GET auth
  includes/class-oauth1-client.php
  includes/steps/class-step-webhook.php
Labels: bug
