Repository gravityflow/gravityflow, pull requests merged in 2020-03, with the labels that each got.

#304 Update filter parameters, docblock and change_log
  change_log.txt
  includes/pages/class-print-entries.php
Labels: bug

#302 Fix workflows stalling on the Dropbox step
  includes/steps/class-step-feed-dropbox.php
Labels: bug

#305 Add workflow note when the Update User step is completed
  change_log.txt
  includes/steps/class-step-update-user.php
Labels: enhancement

#306 Setting to allow the reports shortcode
  change_log.txt
  class-gravity-flow.php
  includes/pages/class-reports.php
Labels: bug, documentation needed

#307 Refine discussion view more/less JS to execute in multiple page contexts
  change_log.txt
  class-gravity-flow.php
  js/entry-detail.js
Labels: bug, documentation needed

#308 Fix missing scripts and styles when using reusable block
  class-gravity-flow.php
  tests/unit-tests/gravity-flow/test-has-shortcode-or-block.php
Labels: bug
