Repository gravityflow/gravityflow, pull requests merged in 2020-06, with the labels that each got.

#323 Enhancements and fixes for the reports block
  class-gravity-flow.php
  includes/pages/class-reports.php
  js/reports.js
  tests/acceptance-tests/acceptance/0043ReportsShortcodeCept.php
  tests/acceptance-tests/acceptance/_bootstrap.php
Labels: documentation needed

#328 Fix an issue with the created_by merge tag
  includes/merge-tags/class-merge-tag-created-by.php
  tests/unit-tests/test-merge-tags.php
Labels: bug

#330 Add support for GravityView's Advanced Filter v2.x
  class-gravity-flow.php
Labels: bug

#331 Approval Step - Require Confirmation apply to revert prompt
  change_log.txt
  includes/steps/class-step-approval.php
  js/step-approval.js
Labels: bug

#333 Fix a fatal error during merge tag replacement with Form Connector
  class-gravity-flow.php
Labels: bug

#332 Fix the reports step assignees dropdown missing issue
  js/reports.js
  tests/acceptance-tests/acceptance/0043ReportsShortcodeCept.php
Labels: bug

#337 Fix non-editable fields required by GP Limit Dates not being retained
  includes/pages/class-entry-editor.php
  tests/acceptance-tests/_data/forms/0044-date-fields.json
  tests/acceptance-tests/acceptance/0044DateFieldsGFMergeTagCept.php
Labels: bug, enhancement
